sudo: false
language: ruby
rvm: 2.4
cache: bundler

before_install:
  - gem update --system
  - gem install bundler

before_script:
  - PR=7136 bundle update

script:
  - git clone --recurse-submodules https://github.com/tomjoht/tomjoht.github.io.git tomjoht-docs
  - PR=7136 bundle exec jekyll build -s tomjoht-docs -d tomjoht-docs/_site --profile
