sudo: false
language: ruby
rvm: 2.4
cache: bundler

branches:
  only:
  - master

before_install:
  - gem update --system
  - gem install bundler

before_script:
  - bundle update

script:
  - PR=7136 ./bench
